[env]
# example: TEST_LOG__LEVEL=debug
prefix = "TEST_"

[log]
# level can be changed at runtime
level = "info"
add_source = false
to_file = true
base_name = "test"
directory = "log"
rotate_size = "100MB"
rotate_interval = "24h" # valid time units are "ns", "us" (or "Âµs"), "ms", "s", "m", "h".
rotate_at_midnight = true